name: Publish

on:
  push:
    tags: 
        - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1      
        with:
          token: ${{ secrets.NPM_TOKEN }} 

  
