name: Build

on:
  push:
    tags: 
        - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: testbranch

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Create Build
        run: yarn build

      - name: Publish
      - uses: JS-DevTools/npm-publish@v1      
        with:
          token: ${{ secrets.NPM_TOKEN }}  
          dryrun: true

  
